Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-24.04"
  config.vm.box_version = "202502.21.0"

  config.vm.hostname = "Harbor"

  config.vm.network "private_network", ip: "192.168.56.220"

#config.vm.network "public_network", bridge: "Killer(TM) Wi-Fi 7 BE1750x 320MHz Wireless Network Adapter (BE200NGW)"


  
  # config.vm.synced_folder "../Ubuntu24.04", "/home/ubuntu"

  # config.vm.synced_folder ".", "/vagrant", disabled: false

  config.vm.provider "virtualbox" do |vb|
  vb.name = "Harbor_registry"
  vb.memory = 4024
  vb.cpus = 4
  end
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
  #   apt-get install -y apache2
  SHELL
end
