Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-24.04"
  config.vm.box_version = "202502.21.0"

  config.vm.hostname = "deployment"

  config.vm.network "private_network", ip: "192.168.56.212"

#  config.vm.network "public_network"


  
  # config.vm.synced_folder "../Ubuntu24.04", "/home/ubuntu"

  # config.vm.synced_folder ".", "/vagrant", disabled: false

  config.vm.provider "virtualbox" do |vb|
  vb.name = "Deployment_Server"
  vb.memory = 3000 
  vb.cpus = 2
  end
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
  #   apt-get install -y apache2
  SHELL
end

