Vagrant.configure("2") do |config|

    config.vm.box = "bento/ubuntu-24.04"
    config.vm.box_version = "202502.21.0"

   config.vm.network "private_network", ip: "192.168.56.250"

   config.vm.network "public_network", bridge: "Killer(TM) Wi-Fi 7 BE1750x 320MHz Wireless Network Adapter (BE200NGW)"

  #  config.vm.synced_folder "../docker_VM", "/vagrant_data"
    config.vm.hostname = "dockerubuntu"

   config.vm.provider "virtualbox" do |vb|
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
      vb.memory = "4000"
      vb.cpus = 4
      vb.name = "Docker"
    end
 config.vm.provision "shell", inline: <<-SHELL
    sudo apt update
    sudo apt install -y ca-certificates curl
    sudo install -m 0755 -d /etc/apt/keyrings
    sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
    sudo chmod a+r /etc/apt/keyrings/docker.asc

    # Add the repository to Apt sources:
    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
      $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | \
      sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    sudo apt update

    sudo apt install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
SHELL
end